name: Create YouTube Video

on:
  workflow_dispatch:

jobs:
  create-video:
    runs-on: ubuntu-latest

    steps:
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download AI voice
        run: |
          curl -fL "https://ai-youtube-automation.waiqqq950.workers.dev/daily-audio" -o voice.mp3
          file voice.mp3
          ls -lh voice.mp3

      - name: Check audio
        run: |
          ffprobe -v error voice.mp3

      - name: Create visual video
        run: |
          ffmpeg -y \
            -f lavfi \
            -i "color=c=black:s=1920x1080:r=30" \
            -i voice.mp3 \
            -filter_complex "
            [0:v]drawtext=text='AI TOOLS & PRODUCTIVITY':fontcolor=white:fontsize=70:x=(w-text_w)/2:y=350,
            drawtext=text='Work Smarter With AI':fontcolor=white:fontsize=45:x=(w-text_w)/2:y=500,
            drawtext=text='Daily AI Tips':fontcolor=white:fontsize=35:x=(w-text_w)/2:y=600
            [v]
            " \
            -map "[v]" \
            -map 1:a \
            -c:v libx264 \
            -preset veryfast \
            -c:a aac \
            -b:a 192k \
            -shortest \
            video.mp4

      - name: Save video
        uses: actions/upload-artifact@v4
        with:
          name: youtube-video
          path: video.mp4
